# Generated by Django 6.0.1 on 2026-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('hall', models.CharField(max_length=10, verbose_name='Зал')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
