# Generated by Django 6.0.1 on 2026-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtaken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='waiting', max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
