# Generated by Django 6.0.1 on 2026-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtaken', '0002_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBanket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
